---
kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/mi-24v/parakeet

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: miwpayou0808/parakeet
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
    when:
      branch:
        - master