---
kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/mohemohe/parakeet

steps:
  - name: slack notification on start
    image: plugins/slack
    settings:
    webhook:
    from_secret: slack_webhook_url
    template: >
      {{repo.owner}}/{{repo.name}} ({{build.branch}}) build #{{build.number}} start: {{build.link}}
    when:
    branch:
      - master

  - name: docker
    image: plugins/docker
    settings:
      repo: mohemohe/parakeet
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
    when:
      branch:
        - master

  - name: slack notification on complete
    image: plugins/slack
    settings:
    webhook:
    from_secret: slack_webhook_url
    template: >
      {{#success build.status}}
         {{repo.owner}}/{{repo.name}} ({{build.branch}}) build #{{build.number}} succeeded: {{build.link}}
      {{else}}
      {{repo.owner}}/{{repo.name}} ({{build.branch}}) build #{{build.number}} failed: {{build.link}}
      {{/success}}
    when:
    branch:
      - master
    status:
      - success
      - failure